// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using armavir.transport.dal;

#nullable disable

namespace armavir.transport.dal.Migrations
{
    [DbContext(typeof(ArmavirTransportContext))]
    [Migration("20251230212737_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("armavir.transport.dal.Entities.Stops", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Stops", (string)null);
                });

            modelBuilder.Entity("armavir.transport.dal.Entities.TransportStops", b =>
                {
                    b.Property<Guid>("TransportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StopId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.HasKey("TransportId", "StopId", "Direction");

                    b.HasIndex("StopId");

                    b.HasIndex("TransportId");

                    b.HasIndex("StopId", "Direction");

                    b.HasIndex("TransportId", "Direction");

                    b.ToTable("TransportStops", (string)null);
                });

            modelBuilder.Entity("armavir.transport.dal.Entities.Transports", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("LongRoute")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("ShortRoute")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Transports", (string)null);
                });

            modelBuilder.Entity("armavir.transport.dal.Entities.TransportStops", b =>
                {
                    b.HasOne("armavir.transport.dal.Entities.Stops", "Stop")
                        .WithMany("TransportStops")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armavir.transport.dal.Entities.Transports", "Transport")
                        .WithMany("Stop")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("armavir.transport.dal.Entities.Stops", b =>
                {
                    b.Navigation("TransportStops");
                });

            modelBuilder.Entity("armavir.transport.dal.Entities.Transports", b =>
                {
                    b.Navigation("Stop");
                });
#pragma warning restore 612, 618
        }
    }
}
